### ISSUE TITLE
Add fancybox as widget

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidifyLibraries#17]
fancybox.html

``` js
/* give images a fancybox and thumbnail classes to allow lightbox and thumbnails */
/* Code from Jim Hester knitr-bootstrap */

$('p').each(function(){
   $(this).children('img')
     .unwrap()
     .wrapAll('<ul class="thumbnails" />')
     .wrap('<li class="span4"><a href="#" class="thumbnail"></a></li>')
     .addClass('fancybox');
});

/* fancybox */
$(".fancybox").each( function() {
  var img = $(this);
  $(this).fancybox({
    beforeLoad: function(){
      <!--img.removeClass('thumbnail');-->
    },
    afterClose: function(){
      <!--img.addClass('thumbnail');-->
      img.css('display', 'block');
     },
   });
});
```

**Comment by ramnathv** [comment]
config.yml

``` yml
fancybox: 
   css: http://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.css
   jshead: http://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.js
```
