### ISSUE TITLE
Add tocify as widget

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidifyLibraries#18]
**config.yml**

``` yml
tocify:
  css: [jquery.tocify.css, bootstrap.min.css]
  jshead: [jquery.min.js, jquery-ui.min.js, jquery.tocify.min.js]
```

**tocify.html**

``` js
//Executes your code when the DOM is ready.  Acts the same as $(document).ready().
$(function() {
  $("#toc").tocify();
});
```

Include HTML

``` html
<div id='toc'></div>
```
