### ISSUE TITLE
Fix list margin in Slidify.css

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidifyLibraries#19]
[These lines](https://github.com/ramnathv/slidifyLibraries/blob/dev/inst/libraries/frameworks/io2012/css/slidify.css#L193-L197) need to be fixed. I think I should change `margin-left` to 1 em to avoid huge margins.

``` css
ol {
  margin-left: 5em;
  margin-bottom: 1em;
  postion: relative;
}
```
