### ISSUE TITLE
Prettify does not play well with minimal

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidifyLibraries#26]
The line numbers are shifted. Easy to fix using 

``` css
ol.linenums {
  margin-left: -5px;
}
```
