### ISSUE TITLE
Simplify deck.js layout

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidifyLibraries#6]
I can simplify the base layout and allow for more flexibility by using configuration files.

**Comment by ramnathv** [comment]
This would be the default `config.yml`

```
deckjs:
  theme: swiss
  transition: horizontal-slide
  extensions: [goto, menu, navigation, navigation, status, hash, scale]
```
